name: Manual PDF Build
on:
  workflow_dispatch: # Only runs on click

permissions:
  contents: write # Required to push the PDF back to your repo

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      - name: Move PDF to assets
        run: |
          mkdir -p assets
          mv resume.pdf assets/cv.pdf

      - name: Commit and Push PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated CV update"
          file_pattern: 'assets/cv.pdf'
